# This is a local copy of https://github.com/folio-org/stripes-smart-components/tree/main/lib/EntryManager
# See https://folio-org.atlassian.net/browse/UIHAADM-76 and https://folio-org.atlassian.net/browse/UIHAADM-160
sonar.exclusions=src/smart-components/**
sonar.coverage.exclusions=src/smart-components/**
