import React from 'react';
import { BrowserRouter } from 'react-router-dom';
import { render, screen } from '@folio/jest-config-stripes/testing-library/react';
import { Paneset } from '@folio/stripes/components';
import withIntlConfiguration from '../../test/jest/util/withIntlConfiguration';
import FullJobRoute, { FullJobRoute as RawFullJobRoute } from './FullJobRoute';
import fullJob from '../../test/jest/data/fullJob';
import transformation from '../../test/jest/data/transformation';
import failedRecords from '../../test/jest/data/failedRecords';
import logs from '../../test/jest/data/logs';


const renderFullJobRoute = (jobResource) => {
  return render(withIntlConfiguration(
    <BrowserRouter>
      <Paneset>
        <FullJobRoute
          stripes={{
            logger: {
            },
          }}
          resources={{
            query: {},
            job: jobResource,
            transformationPipeline: {
              records: [transformation],
            },
            failedRecords: {
              records: [{ failedRecords }],
              totalRecords: failedRecords.length,
            },
            logs: {
              records: logs,
            },
          }}
          mutator={{
            query: {
              update: () => undefined,
            },
            job: {
              DELETE: () => undefined,
            },
            pause: {
              POST: () => undefined,
            },
            resume: {
              POST: () => undefined,
            },
          }}
          match={{
            params: {
              recId: '12345',
            },
          }}
        >
          <div />
        </FullJobRoute>
      </Paneset>
    </BrowserRouter>
  ));
};


describe('Full job route', () => {
  it('should be rendered with data', async () => {
    const node = renderFullJobRoute({
      records: [fullJob],
    });
    // screen.debug();
    const { container } = node;
    const content = container.querySelector('[data-test-full-job-pane]');
    expect(container).toBeVisible();
    expect(content).toBeVisible();

    // Data rendered in display
    for (const [name, value] of [
      ['channelName', 'Minerva5 samples'],
      ['transformationPipeline', 'PICA to FOLIO'],
    ]) {
      const kvRoot = screen.getByText(`ui-inventory-import.jobs.field.${name}`).closest('.kvRoot');
      expect(kvRoot.querySelector('[data-test-kv-value]')).toHaveTextContent(value);
    }
  });
});

describe('Correct paths generated by manifest functions', () => {
  const testCases = [{
    manifestKey: 'transformationPipeline',
    expected: 'inventory-import/transformations/12345',
  }, {
    manifestKey: 'pause',
    expected: 'inventory-import/channels/abcde/pause-job',
  }, {
    manifestKey: 'resume',
    expected: 'inventory-import/channels/abcde/resume-job',
  }];

  for (const { manifestKey, expected } of testCases) {
    it(`${manifestKey} path`, () => {
      const pathFn = RawFullJobRoute.manifest[manifestKey].path;
      const path = pathFn(undefined, undefined, {
        job: {
          records: [
            {
              channelId: 'abcde',
            }
          ]
        }
      }, undefined, {
        resources: {
          job: {
            records: [
              {
                transformation: '12345',
              },
            ],
          },
        }
      });
      expect(path).toBe(expected);
    });
  }
});
